import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import perfil from "../assets/perfil.png";
import { HiDownload } from "react-icons/hi";
import { motion } from "framer-motion";
import About from "../components/About";
import Experience from "@/components/Experience";
import Projects from "@/components/Projects/Projects";
import Contact from "@/components/Contact";
import banner from "../assets/banner-bg.png";
import NavBar from "@/components/NavBar";
import { useState, useEffect } from "react";
import { TypeAnimation } from "react-type-animation";

export default function Home() {
  const [animationKey, setAnimationKey] = useState(0);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  const handleAnimationEnd = () => {
    setAnimationKey(animationKey + 1);
  };

  useEffect(() => {
    document.getElementById("home").scrollIntoView({ behavior: "smooth" });
  }, []);

  return (
    <>
      <Head>
        <title>Portfolio - Alejo Andino</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* NAVBAR Section */}
      <NavBar />

      {/* HOME Section */}
      <div
        className="flex flex-col md:flex-row justify-around items-center md:h-[100vh] bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: `url(${banner.src})` }}
        id="home"
      >
        <motion.div
          className="w-full md:w-[50%] flex flex-col justify-center items-center px-5 md:px-0"
          initial={{ y: 200, opacity: 0, scale: 1 }}
          animate={{ y: 0, opacity: 1, scale: 1 }}
          transition={{ duration: 2, delay: 0.5, ease: "easeInOut" }}
        >
          <p className="text-light font-semibold">Hello Welcome!</p>
          <h1 className="text-4xl md:text-6xl my-3 text-light font-bold text-center md:text-left">
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#4352f1] to-[#6943db]">
              Im Alejo Andino a
            </span>
            <br />
            <TypeAnimation
              sequence={[
                "Full Stack Developer",
                1000,
                "Front-End Developer",
                1000,
                "Back-End Developer",
                1000,
              ]}
              wrapper="span"
              speed={50}
              repeat={Infinity}
            />
          </h1>
          <h2 className="text-light my-5 text-center md:text-left">
            Full-Stack developer specialized in turning ideas into innovative
            web applications. Experience in React.js (Next.js) and web
            development. If you&apos;re looking to take your ideas to the next
            level, Contact me!
          </h2>
          <Link
            className="font-bold"
            href={"/#contact"}
            onClick={(e) => {
              e.preventDefault();
              document.getElementById("contact").scrollIntoView({
                behavior: "smooth",
              });
            }}
          >
            <button className="w-[100px] h-[40px] my-4 mx-6 rounded-full bg-white">
              Hire me
            </button>
          </Link>

          <div className="inline-flex relative">
            <button
              className="px-1 inline-block py-1 w-full sm:w-fit rounded-full bg-gradient-to-br from-primary to-blue-800 hover:bg-slate-800 text-white mt-3"
              onClick={() => setIsDropdownOpen("open")}
            >
              <span className="flex items-center bg-[#121212] hover:bg-slate-800 rounded-full px-5 py-2">
                Download CV
                <HiDownload className="opacity-60 group-hover:translate-y-1 transition ml-1" />
              </span>
            </button>

            {isDropdownOpen && (
              <div className="z-20 absolute mt-2 left-0 top-full w-48 bg-white rounded-lg shadow-md bg-gradient-to-br from-[#0c0d2a] to-[#081b50]">
                <div className="flex justify-end px-2 py-1">
                  <button
                    className="text-white rounded-md p-1 bg-red-600 hover:bg-red-800"
                    onClick={() => setIsDropdownOpen(false)}
                  >
                    X
                  </button>
                </div>
                <button
                  onClick={() => {
                    setIsDropdownOpen(false);
                  }}
                  className="inline-flex rounded-md justify-center px-4 py-2 text-white hover:bg-slate-900 w-full text-left"
                >
                  <a
                    href="/Alejo_Andino_Resume_3.0.pdf"
                    download={"Alejo_Andino_Resume_3.0.pdf"}
                  >
                    Spanish
                  </a>
                </button>
                <button
                  onClick={() => {
                    setIsDropdownOpen(false);
                  }}
                  className="inline-flex rounded-md justify-center px-4 py-2 text-white hover:bg-slate-900 w-full text-left"
                >
                  <a
                    href="/Alejo-Andino-Resume-English-3.0.pdf"
                    download={"Alejo-Andino-Resume-English-3.0.pdf"}
                  >
                    English
                  </a>
                </button>
              </div>
            )}
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, scale: 0 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{
            duration: 0.8,
            delay: 0.5,
            ease: [0, 0.71, 0.2, 1.01],
          }}
          className="relative flex justify-center items-center w-[380px] md:w-[50%]"
        >
          <Image
            className="rounded-full relative h-[450px] w-[320px] flex justify-center items-center"
            src={perfil}
            width={300}
            height={300}
            alt="perfil"
            style={{ zIndex: 10 }}
          />
          <svg
            viewBox="0 0 500 500"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            width="100%"
            id="blobSvg"
            className="absolute w-full h-full"
            style={{ filter: "blur(1px)" }}
          >
            <path fill="#2057d8">
              <animate
                attributeName="d"
                dur="5000ms"
                repeatCount="indefinite"
                values="..."
                key={animationKey}
                onAnimationEnd={handleAnimationEnd}
              />
            </path>
          </svg>

          <svg
            viewBox="0 0 500 500"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            width="100%"
            id="blobSvg"
            className="absolute w-full h-full"
            style={{ filter: "blur(50px)" }}
          >
            <path fill="#2057d8">
              <animate
                attributeName="d"
                dur="7000ms"
                repeatCount="indefinite"
                values="..."
                key={animationKey}
                onAnimationEnd={handleAnimationEnd}
              />
            </path>
          </svg>
        </motion.div>

        <div className="text-light mt-10 text-center md:text-right">
          <div className="mb-10">
            <p className="text-4xl text-end mb-3">6M+</p>
            <h3 className="text-xl text-end font-bold">Experiencie</h3>
          </div>

          <div className="mb-10">
            <p className="text-4xl text-end mb-3">4</p>
            <h3 className="text-xl text-end font-bold">Projects Completed</h3>
          </div>
        </div>
      </div>

      {/* About Section */}
      <About />

      {/* Projects Section */}
      <Projects />

      {/* Experience Section */}
      <Experience />

      {/* Contact Section */}
      <Contact />
    </>
  );
}
