import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import perfil from "../assets/perfil.png";
import { HiDownload } from "react-icons/hi";
import { motion } from "framer-motion";
import About from "../components/About";
import Experience from "@/components/Experience";
import Projects from "@/components/Projects/Projects";
import Contact from "@/components/Contact";
import banner from "../assets/banner-bg.png";
import NavBar from "@/components/NavBar";
import { useState, useEffect } from "react";
import { TypeAnimation } from "react-type-animation";

export default function Home() {
  const [animationKey, setAnimationKey] = useState(0);
  //Para menu Desplegable
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  const handleAnimationEnd = () => {
    setAnimationKey(animationKey + 1);
  };

  useEffect(() => {
    // Scroll to the home section when the page mounts
    document.getElementById("home").scrollIntoView({ behavior: "smooth" });
  }, []);

  return (
    <>
      <Head>
        <title>Portfolio - Alejo Andino</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* NAVBAR Section */}
      <NavBar />

      {/* HOME Section */}
      <div
        className="overflow-hidden md:pt-0"
        // style={{
        //   backgroundImage: `url(${banner.src})`,
        // }}
      >
        <div
          className="flex justify-around pt-12 items-center h-full md:h-screen bg-cover bg-center bg-no-repeat"
          style={{
            backgroundImage: `url(${banner.src})`,
          }}
          id="home"
        >
          <motion.div
            className="flex flex-col items-center w-full p-4 relative md:flex-row"
            initial={{ y: 200, opacity: 0, scale: 1 }}
            animate={{ y: 0, opacity: 1, scale: 1 }}
            transition={{
              duration: 2,
              delay: 0.5,
              ease: "easeInOut",
            }}
          >
            <section className="md:w-[1300px] md:ml-8">
              <p className="m-3 text-light text-center md:text-start font-semibold md:mb-10">
                Hello Welcome!
              </p>
              <h1 className="text-[33px] w-full text-center md:text-start md:text-7xl sm:text-5xl my-3 text-light font-extrabold">
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#4352f1] to-[#6943db]">
                  Im Alejo Andino a
                </span>
                <br></br>
                <TypeAnimation
                  sequence={[
                    "Full Stack Developer",
                    1000,
                    "Front-End Developer",
                    1000,
                    "Back-End Developer",
                    1000,
                  ]}
                  wrapper="span"
                  speed={50}
                  repeat={Infinity}
                />
              </h1>
              <h2 className="text-light text-center md:text-start md:text-base my-5 text-sm font-extrabold">
                Full-Stack developer specialized in turning ideas into
                innovative web applications. Experience in React.js (Next.js)
                and web development. If you&apos;re looking to take your ideas
                to the next level, Contact me!
              </h2>
              <div
                id="buttonsHome"
                className="w-full px-16 mt-3 flex flex-col md:flex-row md:justify-start md:px-0 md:gap-5"
              >
                <Link
                  className="font-bold text-center flex flex-col justify-center"
                  href={"/#contact"}
                  onClick={(e) => {
                    e.preventDefault();
                    document.getElementById("contact").scrollIntoView({
                      behavior: "smooth",
                    });
                  }}
                >
                  <button className="w-full md:w-40 h-[40px] rounded-full bg-white">
                    Hire me
                  </button>
                </Link>

                <div className="font-bold inline-flex justify-center relative">
                  <button
                    className="px-1 items-center inline-block py-1 w-full rounded-full bg-gradient-to-br from-primary to-blue-800 hover:bg-slate-800 text-white mt-3 md:mt-0"
                    onClick={() => setIsDropdownOpen("open")}
                  >
                    <span className="flex justify-center bg-[#121212] hover:bg-slate-800 rounded-full px-5 py-2">
                      Download CV
                      <HiDownload className="opacity-60 group-hover:translate-y-1 transition ml-1" />
                    </span>
                  </button>

                  {isDropdownOpen && (
                    <div className="absolute z-20 mt-2 left-8 md:left-0 top-full w-48 bg-white rounded-lg shadow-md bg-gradient-to-br from-[#0c0d2a] to-[#081b50]">
                      <div className="flex justify-end px-2 py-1">
                        <button
                          className="text-white rounded-md p-1 bg-red-600 hover:bg-red-800"
                          onClick={() => setIsDropdownOpen(false)}
                        >
                          X
                        </button>
                      </div>
                      <button
                        onClick={() => {
                          setIsDropdownOpen(false);
                        }}
                        className="inline-flex rounded-md justify-center px-4 py-2 text-white hover:bg-slate-900 w-full text-left"
                      >
                        <a
                          href="/Alejo_Andino_Resume_3.0.pdf"
                          download={"Alejo_Andino_Resume_3.0.pdf"}
                        >
                          Spanish
                        </a>
                      </button>
                      <button
                        onClick={() => {
                          setIsDropdownOpen(false);
                        }}
                        className="inline-flex rounded-md justify-center px-4 py-2 text-white hover:bg-slate-900 w-full text-left"
                      >
                        <a
                          href="/Alejo-Andino-Resume-English-3.0.pdf"
                          download={"Alejo-Andino-Resume-English-3.0.pdf"}
                        >
                          English
                        </a>
                      </button>
                    </div>
                  )}
                </div>
              </div>
            </section>

            <motion.div
              initial={{ opacity: 0, scale: 0 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{
                duration: 4.8,
                delay: 0.5,
                ease: [0, 0.71, 0.2, 1.01],
              }}
              className="relative flex justify-center items-center w-[380px] md:w-[600px]"
            >
              <svg
                viewBox="0 0 500 500"
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                width="100%"
                id="blobSvg"
                className="absolute w-full h-full"
                style={{ filter: "blur(1px)" }}
              >
                <path fill="#2057d8">
                  <animate
                    attributeName="d"
                    dur="5000ms"
                    repeatCount="indefinite"
                    values="
          M449.5,326.5Q403,403,326.5,429Q250,455,177,425.5Q104,396,93.5,323Q83,250,84,167.5Q85,85,167.5,82.5Q250,80,309.5,105.5Q369,131,432.5,190.5Q496,250,449.5,326.5Z;
          M406.5,329.5Q409,409,329.5,439.5Q250,470,175.5,434.5Q101,399,84,324.5Q67,250,102,193.5Q137,137,193.5,117Q250,97,322.5,101Q395,105,399.5,177.5Q404,250,406.5,329.5Z;
          M420,313.5Q377,377,313.5,436.5Q250,496,182,441Q114,386,104.5,318Q95,250,113,190.5Q131,131,190.5,91.5Q250,52,321,80Q392,108,427.5,179Q463,250,420,313.5Z;
          M429,324Q398,398,324,411.5Q250,425,170.5,417Q91,409,62.5,329.5Q34,250,74,182Q114,114,182,80Q250,46,316.5,81.5Q383,117,421.5,183.5Q460,250,429,324Z;
          M441,338Q426,426,338,440Q250,454,177,425Q104,396,61.5,323Q19,250,71.5,187Q124,124,187,70.5Q250,17,327.5,56Q405,95,430.5,172.5Q456,250,441,338Z;
          M448.5,330.5Q411,411,330.5,452Q250,493,182.5,439Q115,385,94.5,317.5Q74,250,78.5,166.5Q83,83,166.5,77.5Q250,72,326.5,84.5Q403,97,444.5,173.5Q486,250,448.5,330.5Z;
          M449.5,326.5Q403,403,326.5,429Q250,455,177,425.5Q104,396,93.5,323Q83,250,84,167.5Q85,85,167.5,82.5Q250,80,309.5,105.5Q369,131,432.5,190.5Q496,250,449.5,326.5Z;"
                    key={animationKey}
                    onAnimationEnd={handleAnimationEnd}
                  />
                </path>
              </svg>

              <svg
                viewBox="0 0 500 500"
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                width="100%"
                id="blobSvg"
                className="absolute w-full h-full"
                style={{ filter: "blur(50px)" }}
              >
                <path fill="#2057d8">
                  <animate
                    attributeName="d"
                    dur="7000ms"
                    repeatCount="indefinite"
                    values="
          M449.5,326.5Q403,403,326.5,429Q250,455,177,425.5Q104,396,93.5,323Q83,250,84,167.5Q85,85,167.5,82.5Q250,80,309.5,105.5Q369,131,432.5,190.5Q496,250,449.5,326.5Z;
          M406.5,329.5Q409,409,329.5,439.5Q250,470,175.5,434.5Q101,399,84,324.5Q67,250,102,193.5Q137,137,193.5,117Q250,97,322.5,101Q395,105,399.5,177.5Q404,250,406.5,329.5Z;
          M420,313.5Q377,377,313.5,436.5Q250,496,182,441Q114,386,104.5,318Q95,250,113,190.5Q131,131,190.5,91.5Q250,52,321,80Q392,108,427.5,179Q463,250,420,313.5Z;
          M429,324Q398,398,324,411.5Q250,425,170.5,417Q91,409,62.5,329.5Q34,250,74,182Q114,114,182,80Q250,46,316.5,81.5Q383,117,421.5,183.5Q460,250,429,324Z;
          M441,338Q426,426,338,440Q250,454,177,425Q104,396,61.5,323Q19,250,71.5,187Q124,124,187,70.5Q250,17,327.5,56Q405,95,430.5,172.5Q456,250,441,338Z;
          M448.5,330.5Q411,411,330.5,452Q250,493,182.5,439Q115,385,94.5,317.5Q74,250,78.5,166.5Q83,83,166.5,77.5Q250,72,326.5,84.5Q403,97,444.5,173.5Q486,250,448.5,330.5Z;
          M449.5,326.5Q403,403,326.5,429Q250,455,177,425.5Q104,396,93.5,323Q83,250,84,167.5Q85,85,167.5,82.5Q250,80,309.5,105.5Q369,131,432.5,190.5Q496,250,449.5,326.5Z;"
                    key={animationKey}
                    onAnimationEnd={handleAnimationEnd}
                  />
                </path>
              </svg>

              <Image
                className="rounded-full relative h-[300px] w-[250px] md:w-[350px] md:h-[400px] flex justify-center items-center"
                src={perfil}
                width={300}
                height={300}
                alt="perfil"
                style={{ zIndex: 10 }}
              />
            </motion.div>
            <div className="text-light my-16 flex justify-around w-full md:w-[400px] text-center md:flex-col">
              <div className="mb-10 flex flex-col">
                <p className="text-4xl mb-3">1</p>
                <h3 className="text-xl font-bold">Years of Experiencie</h3>
              </div>

              <div className="mb-10 flex flex-col">
                <p className="text-4xl mb-3">4</p>
                <h3 className="text-xl font-bold">Projects Completed</h3>
              </div>
            </div>
          </motion.div>
        </div>
        {/* About Section */}
        <About />

        {/* Projects Section */}
        <Projects />

        {/* Experience Section */}
        <Experience />

        {/* Contact Section */}
        <Contact />
      </div>
    </>
  );
}
