import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import perfil from "../assets/perfil.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio - Alejo Andino</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex justify-evenly items-center mt-14">
        <div className="w-[300px]">
          <p className="m-3 text-light">Hello Welcome!</p>
          <h1 className="text-3xl my-3 text-light font-bold">Im Alejo Andino a Full Stack Developer</h1>
          <Link className="text-light" href={"/"}>Hire Me</Link>
          <h2 className="text-light">
            As an experienced Full-Stack developer, I am dedicated to turning
            ideas into innovative web applications. Through my latest projects
            and articles, you can discover my skills and expertise in React.js
            and web development. I am committed to creating effective and
            engaging solutions that meet user needs and exceed their
            expectations. If you are looking for a developer who can take your
            ideas to the next level, do not hesitate to contact me.
          </h2>
          <p className="text-light">Follow me:</p>
        </div>

        <div>
          <Image
            className="bg-[#966fbe] rounded-full h-[450px] w-[320px] flex justify-center items-center"
            src={perfil}
            width={300}
            height={300}
            alt="perfil"
          />
        </div>

        <div className="text-light">
          <div>
            <p>1+</p>
            <h3>Years of Experiencie</h3>
          </div>
          <div>
            <p>100%</p>
            <h3>Success Rate</h3>
          </div>
          <div>
            <p>4</p>
            <h3>Projects Completed</h3>
          </div>
        </div>
      </div>
    </>
  );
}
